### ISSUE TITLE
ROCM support AMD Oct 2023

### ISSUE THREAD

**Issue by bennmann** [facebookresearch/doc-storygen-v2#3]
https://github.com/vllm-project/vllm/issues/621 waiting for VLLM updates to test this with AMD card via ROCM

Not sure of other dependency past VLLM - will work to remember to update this issue with news 

I have a simplified way to get completions from local open AI compatible API via koboldcpp (based on llama.cpp), but not logprobs

**Comment by yangkevin2** [comment]
You could turn off the rerankers in the config at https://github.com/facebookresearch/doc-storygen-v2/blob/main/scripts/story/config.yaml#L54 since that's the only place we use the logprobs - you might get worse results but should be easier to run I think.

**Comment by bennmann** [comment]
ok, i commented out 

1) i commented out everything from the SCORE section of config.yaml (line 47 to end)

2)
```
\doc-storygen-v2\scripts> python .\premise\generate.py
C:\...\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py:39: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
  warnings.warn(
2023-10-27 15:29:48 ERROR    Failed to get a valid completion after 5 attempts.
Traceback (most recent call last):
  File "F:\doc-storygen-v2\scripts\premise\generate.py", line 29, in <module>
    generate_title(premise, prompts['title'], config['model']['title'], llm_client)
  File "f:\doc-storygen-v2\storygen\premise\premise_writer.py", line 8, in generate_title
    title = llm_client.call_with_retry(
  File "f:\doc-storygen-v2\storygen\common\llm\llm.py", line 86, in call_with_retry
    raise RuntimeError(f"Failed to get a valid completion after {max_attempts} attempts.")
RuntimeError: Failed to get a valid completion after 5 attempts.
``` 
i am able to curl the localhost endpoint manually:

```
$ curl -H "Content-Type: application/json" -d '{"prompt":"I entered into an argument with a clown", "params":{"n":5}, "api_key":"0000000000"}' http://localhost:5001/api/v1/generate

  201{"results": [{"text": " about the inadvisability of giving children balloon animals, as it was only encouraging their parents to bring them to such places. He made no sense at all and kept arguing from a position of complete illogic. I pointed this out to him calmly and rationally, but he continued to talk nonsense. Eventually, I left the party, disgusted"}]}
``` 
all ideas and help appreciated

**Comment by bennmann** [comment]
this is my model section of config

```
 MODEL:
    engine: "TODO" #TODO # TODO path/to/vllm-supported/hf/model, vllm-supported huggingface model string, or openai model string
    server_type: vllm # "vllm" or "openai"
    host: http://localhost # model server if using vllm
    port: 5001 #9741
    prompt_format: llama2-chat # "none" (pretrained base model), "openai-chat", or "llama2-chat"; add other options in llm.py as needed
    # for the remaining args below, you can put these args here to be shared, or put specific ones under "title" and "premise" if you want different args
    temperature: 0.8
    top_p: 0.6
    frequency_penalty: 1
    presence_penalty: 0
```

**Comment by yangkevin2** [comment]
It definitely shouldn't be failing in the premise generation step, that part is really simple; seems like currently the LLM calls are just not working at all. (I originally thought you were on the story generation step, since you asked about logprobs, and the premise and plan steps don't use logprobs; note there are separate config files for each step.) You could try putting debug stops and looking through what's happening in here https://github.com/facebookresearch/doc-storygen-v2/blob/main/storygen/common/llm/llm.py#L71 to see if the LLM interface is not working somehow (e.g., either the completion isn't in the right format, or outputs are getting filtered out for whatever reason).

**Comment by bennmann** [comment]
```
\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py:39: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
  warnings.warn(
2023-10-27 17:51:36 DEBUG    Starting new HTTPS connection (1): huggingface.co:443
2023-10-27 17:35:22 DEBUG    https://huggingface.co:443 "HEAD /gpt2/resolve/main/tokenizer_config.json HTTP/1.1" 404 0
``` 

looks like langchain needs some " SelfHostedHuggingFaceLLM" argument for local 
https://github.com/langchain-ai/langchain/issues/8931 

not what variable or py to change for that...

**Comment by yangkevin2** [comment]
Er, wait, I just noticed your model engine is "TODO" in the config? I guess you're just hacking it to call your own server instead? This line https://github.com/facebookresearch/doc-storygen-v2/blob/main/storygen/common/llm/llm.py#L120 is where the model server call happens, you can probably inspect what's going on around there. It seems like somehow it's not quite interfacing to your server correctly.

You can ignore the langchain warning.

**Comment by bennmann** [comment]
I will try to figure out an elegant few lines for python requests packages for this soon.

Curl is my HTTP mother tongue, shouldn't be too hard to figure out the requests library equivalent over time though

Might be some many days, if/when I get it working I will update here
